### ISSUE TITLE
Question from a newbie

### ISSUE THREAD

**Issue by elidonner** [mysticuno/wordle-helper#1]
hey mysticuno, really enjoyed your wordle solver! I had the same idea to make one of these to try out some javascript/html and had made my own version before looking at available google extensions and seeing yours. Yours is so much cooler! I was curious if you could help out a total newbie by sharing any resources on the JSON.parse(window ...) you use to get the board state, or how you figured out to do that... I used this ridiculous document.getElement path that sorted through the DOM (including shadow roots) from the html file I saw when inspecting the page. Thanks so much! (also forgive me if writing an issue isn't the way to ask a question like this I am new to github as well)

**Comment by mysticuno** [comment]
Hi @elidonner, welcome to Github! I'm glad you're enjoying the extension, and I'm happy to help in any way I can!

I don't remember where exactly I saw it, but it might have been on Twitter that someone mentioned that the `solution` (and the rest of the Wordle state) were stored locally. `window.localStorage` is commonly used to store any information that you want across browser sessions. That's how Wordle can keep track of your streak even if you've closed the page and then come back to it later; the browser will store that data, and the Wordle page will load it when you revisit. However, because it's browser specific, you won't have that data shared across different browsers like Chrome and Firefox (unless you do something a bit fancier). [Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API) has an awesome article about using the Web Storage API.

Poking around `window.localStorage` I was able to see that there some other things stored locally, and that `nyt-wordle-state` was stored as one big [JSON](https://developer.mozilla.org/en-US/docs/Glossary/JSON) string:
![image](https://user-images.githubusercontent.com/6826622/157567461-e476ade4-800d-416f-bfbb-57ccbb9a4b2b.png)
![image](https://user-images.githubusercontent.com/6826622/157568064-71e2ab8f-cbc1-40fa-817a-4905ba1d7f4d.png)

Once I saw that the state was a JSON string, I wanted to turn it into an object that I could play around with more easily, and `JSON.parse()` does exactly that. [JSON.parse()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) is a method that will take in a JSON string and turn it into an actual object whose properties we can access:
![image](https://user-images.githubusercontent.com/6826622/157568390-8396a530-7e37-4800-8137-22e47d0900b1.png)

This makes it easier to see what the updated game state is rather than having to parse the string itself or derive the state based on what the HTML elements are after the player inputs a guess:
![image](https://user-images.githubusercontent.com/6826622/157568588-4556e559-26ce-42e0-94fd-410bb6db554a.png)

Once I had access to the evaluations, I was able to filter down the list of possible words and then update that in the extension popup. 

Let me know if any of that was confusing, and I can take another stab at explaining :) Hope that helps! I'm also happy to answer any other questions you have about how the code works

**Comment by elidonner** [comment]
Wow, @mysticuno I'm speechless. This is such a kind and helpful response!

I was completely unaware of the `windows.localStorage`, that article from Mozilla was so helpful. Thanks for taking the time to write out such a detailed response.

I went ahead and used this in my extension and I poached some of your css and html as well to get the nice scrolling output! Thanks! As soon as I figure out how these SSH keys work I'm going to upload my version, my solver isn't as cool or sleek as yours, but it does the trick.

Thanks again, this was such a great first experience asking a stranger for help online... can't wait to pay it forward someday, have a good one!
